name: "My first GitHub Actions"
on: [push] 
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install nodejs
            uses: actions/setup-node@v2
            with:
              node-version: '14.17.0'
          - name: Install node modules
            run: yarn
          - name: Build the project
            run: yarn build
          - name: Setup finish
            run: echo "hurray!"
